version: "3.9"

services:
  celery:
    container_name: celery
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint:
      - ./scripts/celery-entrypoint.prod.sh
    volumes:
      - shared-volume:/home/app
    env_file:
      - config/.env.prod.rabbitmq
      - config/.env.prod.django
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - redis_password
      - postgres_password
    depends_on:
      - backend
      - rabbitmq
    networks:
      - quiz

  # Deploy the broker.
  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    image: rabbitmq:3-management-alpine
    env_file:
      - config/.env.prod.rabbitmq
    expose:
      - 5672
    networks:
      - quiz

  backend:
    container_name: backend
    env_file:
      - config/.env.prod
      - config/.env.prod.django
      - config/.env.prod.rabbitmq
      - config/.env.prod.db
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - redis_password
      - postgres_password
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint:
      - ./scripts/server-entrypoint.prod.sh
    command: gunicorn app.wsgi --bind ${DJANGO_HOST?}:${DJANGO_PORT?} --workers 4 --threads 4
    ports:
      - ${DJANGO_PORT?}:${DJANGO_PORT?}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - shared-volume:/home/app
    links:
      - db
    networks:
      - quiz

  db:
    container_name: db
    image: postgres:15.2-alpine
    restart: unless-stopped
    env_file:
      - config/.env.prod.db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 1s
      retries: 5
    expose:
      - 5432
    volumes:
      - postgres_db:/var/lib/postgresql
    networks:
      - quiz

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password
    command: sh -c "redis-server --requirepass $(cat $$REDIS_PASSWORD_FILE) && echo $(cat $$REDIS_PASSWORD_FILE)"
    expose:
      - 6379
    volumes:
      - cache:/var/lib/redis/data
    networks:
      - quiz

networks:
  quiz:
    name: quiz
    driver: bridge

volumes:
  postgres_db:
    driver: local
  cache:
    driver: local

secrets:
  redis_password:
    file: ./secrets/redis-password.txt
  postgres_password:
    file: ./secrets/postgres-password.txt