# Generated by Django 4.2.2 on 2023-06-18 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="users",
        ),
        migrations.AddField(
            model_name="quiz",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quizzes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator id",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="passed_users",
            field=models.ManyToManyField(
                through="quiz.Take", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
