# Generated by Django 4.2.2 on 2023-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_remove_quiz_users_quiz_creator_quiz_passed_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="file_name",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="source_id",
            new_name="source",
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="material name"
            ),
        ),
    ]
