# Generated by Django 4.2.2 on 2023-06-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_alter_quiz_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqquestion",
            name="options",
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.mcqquestion",
                verbose_name="question",
            ),
        ),
    ]
