# Generated by Django 4.2.2 on 2023-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0008_alter_mcqquestion_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insertionquestion",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="question id"
            ),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="question id"
            ),
        ),
        migrations.AlterField(
            model_name="openendedquestion",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="question id"
            ),
        ),
        migrations.AlterField(
            model_name="truefalsequestion",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="question id"
            ),
        ),
    ]
