# Generated by Django 4.2.2 on 2023-06-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0011_alter_mcqquestion_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqquestion",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
                verbose_name="question id",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
