# Generated by Django 4.2.2 on 2023-06-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0014_alter_mcqquestion_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqquestion",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="source",
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="correct",
            field=models.BooleanField(default=False, verbose_name="correct"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="sources",
            field=models.ManyToManyField(to="quiz.material", verbose_name="sources"),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="question",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="mcq_question",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
    ]
