# Generated by Django 4.2.2 on 2023-06-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0014_alter_mcqquestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqquestion",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="MCQQuestion",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
    ]
