# Generated by Django 4.2.2 on 2023-06-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0015_alter_mcqquestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqquestion",
            name="question",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="mcq_question",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
    ]
