# Generated by Django 4.2.2 on 2023-06-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0016_alter_mcqquestion_question_alter_question_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.material",
                verbose_name="source id",
            ),
        ),
    ]
