# Generated by Django 4.2.2 on 2023-06-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0016_alter_mcqquestion_question_alter_question_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqquestion",
            name="answer",
        ),
        migrations.AddField(
            model_name="mcqoption",
            name="correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
