# Generated by Django 4.2.2 on 2023-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0016_quiz_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="ready",
            field=models.BooleanField(default=False),
        ),
    ]
