# Generated by Django 4.2.2 on 2023-06-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0016_quiz_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insertionquestion",
            name="id",
        ),
        migrations.RemoveField(
            model_name="openendedquestion",
            name="id",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="id",
        ),
        migrations.AddField(
            model_name="insertionquestion",
            name="question",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="insertion_questions",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
        migrations.AddField(
            model_name="openendedquestion",
            name="question",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="open_ended_questions",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
        migrations.AddField(
            model_name="truefalsequestion",
            name="question",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="true_false_questions",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="question",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="mcq_questions",
                serialize=False,
                to="quiz.question",
                verbose_name="question id",
            ),
        ),
    ]
