# Generated by Django 4.2.2 on 2023-06-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0017_remove_insertionquestion_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insertionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insertion_answers",
                to="quiz.insertionquestion",
                verbose_name="question id",
            ),
        ),
    ]
