# Generated by Django 4.2.2 on 2023-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0017_alter_quiz_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="source",
        ),
        migrations.AddField(
            model_name="quiz",
            name="sources",
            field=models.ManyToManyField(
                null=True, to="quiz.material", verbose_name="sources"
            ),
        ),
    ]
