# Generated by Django 4.2.2 on 2023-06-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0017_remove_mcqquestion_answer_mcqoption_correct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="source",
        ),
        migrations.AddField(
            model_name="mcqquestion",
            name="answer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="quiz.mcqoption",
                verbose_name="answer id",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="sources",
            field=models.ManyToManyField(
                null=True, to="quiz.material", verbose_name="sources"
            ),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="correct",
            field=models.BooleanField(default=False, verbose_name="correct"),
        ),
        migrations.AlterField(
            model_name="mcqoption",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="option id"
            ),
        ),
    ]
