# Generated by Django 4.2.2 on 2023-06-30 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0017_quiz_ready"),
        ("quiz", "0018_alter_insertionanswer_question"),
    ]

    operations = []
