# Generated by Django 4.2.2 on 2023-06-26 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0018_remove_quiz_source_mcqquestion_answer_quiz_sources_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqquestion",
            name="answer",
        ),
    ]
