# Generated by Django 4.2.2 on 2023-06-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0019_remove_mcqquestion_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="sources",
            field=models.ManyToManyField(to="quiz.material", verbose_name="sources"),
        ),
    ]
