# Generated by Django 4.2.2 on 2023-07-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0022_quiz_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="description",
        ),
    ]
