# Generated by Django 4.2.2 on 2023-07-08 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_quiz_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 8, 22, 21, 23, 274878), verbose_name='datetime')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='quiz.quiz')),
            ],
        ),
    ]
