# Generated by Django 4.2.2 on 2023-07-08 23:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0026_alter_quizview_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizview",
            name="datetime",
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="quizview",
            name="viewed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quizview",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="quizview",
            name="quiz",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="quiz.quiz",
            ),
            preserve_default=False,
        ),
    ]
