# Generated by Django 4.2.2 on 2023-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0028_quizview_viewer_alter_mcqoption_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqoption",
            name="text",
            field=models.CharField(max_length=150, verbose_name="option text"),
        ),
    ]
