# Generated by Django 4.2.2 on 2023-07-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0029_alter_mcqoption_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqoption',
            name='text',
            field=models.CharField(max_length=200, verbose_name='option text'),
        ),
        migrations.AlterField(
            model_name='take',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='quiz id'),
        ),
        migrations.AlterField(
            model_name='take',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
    ]
