"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import urllib.parse
from datetime import timedelta
from pathlib import Path

import environ
import redis

from app.SearchDB import SearchDB

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SEARCH_DB = SearchDB(env('SEARCH_DB_PATH', default="nagim_db"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(env("DEBUG", default=1))

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS", default="").split(" ")

# Celery settings
# RABBITMQ_PASSWORD_FILE = env("REDIS_PASSWORD_FILE", default=None)
# RABBITMQ_PASSWORD = open(RABBITMQ_PASSWORD_FILE).read() if RABBITMQ_PASSWORD_FILE else "password"
RABBITMQ_PASSWORD = env("RABBITMQ_PASSWORD", default="guest")
RABBITMQ = {
    "PROTOCOL": env("RABBITMQ_PROTOCOL", default="amqp"),  # in prod change with "amqps"
    "HOST": env("RABBITMQ_HOST", default="localhost"),
    "PORT": env("RABBITMQ_PORT", default=5672),
    "USER": env("RABBITMQ_USER", default="guest"),
    "PASSWORD": RABBITMQ_PASSWORD,
}

REDIS_PASSWORD_FILE = env("REDIS_PASSWORD_FILE", default=None)
REDIS_PASSWORD = open(REDIS_PASSWORD_FILE).read() if REDIS_PASSWORD_FILE else "password"
REDIS = {
    "PROTOCOL": env("REDIS_PROTOCOL", default="redis"),
    "HOST": env("REDIS_HOST", default="localhost"),
    "PORT": env("REDIS_PORT", default=6379),
    "DATABASE": env("REDIS_DATABASE", default=0),
    "PASSWORD": REDIS_PASSWORD
}

# Redis Django settings

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"{REDIS['PROTOCOL']}://:{REDIS['PASSWORD']}@{REDIS['HOST']}:" \
                    f"{REDIS['PORT']}/{REDIS['DATABASE']}",

        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

CELERY_BROKER_URL = f"{RABBITMQ['PROTOCOL']}://{RABBITMQ['USER']}:" \
                    f"{RABBITMQ['PASSWORD']}@{RABBITMQ['HOST']}:{RABBITMQ['PORT']}"

CELERY_RESULT_BACKEND = f"{REDIS['PROTOCOL']}://:{REDIS['PASSWORD']}@{REDIS['HOST']}:" \
                        f"{REDIS['PORT']}/{REDIS['DATABASE']}"
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "authorization",
    'corsheaders',
    "quiz",
]

CORS_ORIGIN_ALLOW_ALL = bool(env('CORS_ALLOW_ALL', default=1))
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS').split(" ") if not CORS_ORIGIN_ALLOW_ALL else []

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "app.urls"

# Rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

ALGORITHM = env("ALGORITHM", default="RS256")
SIGNING_KEY = open(env('PRIVATE_KEY_PATH', default='jwtRS256.key')).read() if 'RS' in ALGORITHM else SECRET_KEY

# Simple JWT settings
SIMPLE_JWT = {
    "ALGORITHM": env("ALGORITHM", default="RS256"),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "SIGNING_KEY": SIGNING_KEY,
    "VERIFYING_KEY": open(
        f"{env('PRIVATE_KEY_PATH', default='jwtRS256.key')}.pub"
    ).read() if 'RS' in ALGORITHM else "",
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


POSTGRES_PASSWORD_FILE = env("POSTGRES_PASSWORD_FILE", default=None)
POSTGRES_PASSWORD = open(POSTGRES_PASSWORD_FILE).read() if POSTGRES_PASSWORD_FILE else "password"

DATABASES = {
    'default': {
        'ENGINE': env("DB_ENGINE", default="django.db.backends.sqlite3"),
        'NAME': env("DB_NAME", default=os.path.join(BASE_DIR, "db.sqlite3")),
        'USER': env("DB_USER", default="user"),
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': env("DB_HOST", default="localhost"),
        'PORT': env("DB_PORT", default="5432"),
    }
}

# User model
AUTH_USER_MODEL = "authorization.User"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Password hashers
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
