name: python-linter
on: [push, pull_request]
jobs:
  linters:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install pylint_django
          pip install pylint
      - name: Lint with flake8
        run: |
          flake8 $(git ls-files '*.py') --count --select=E9,F63,F7,F82 --exclude=*/migrations/* --show-source --statistics
          flake8 $(git ls-files '*.py') --count --max-complexity=10 --max-line-length=79 --exclude=*/migrations/* --statistics
      - name: Run pylint tests
        uses: Silleellie/pylint-github-action@v1
        with:
          package-path: .  # lint src package
          python-version: 3.10.2