name: python-linter
on: [ push, pull_request ]
jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 $(git ls-files '*.py') --count --select=E9,F63,F7,F82 --exclude=*/migrations/* --show-source --statistics
          flake8 $(git ls-files '*.py') --count --max-complexity=10 --max-line-length=79 --exclude=*/migrations/* --statistics
  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint_django
          pip install pylint
      - name: Run pylint test
        run: |
          pylint $(git ls-files '*.py') | tee result.txt
#  generate_badge:
#    runs-on: ubuntu-20.04
#    if: github.ref == 'refs/heads/main'
#    needs: pylint
#    steps:
#      - name: Build badge
#        run: |
#          mkdir -p badges
#          anybadge --value=$(cat result.txt | sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p') --file=badges/pylint.svg pylint
#      - name: Deploy badge
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
#          publish_branch: main


      
          

